# Generated by Django 5.2.8 on 2025-12-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('idTipoUva', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DenominacionOrigen',
            fields=[
                ('idDenominacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='main.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominacion', to='main.denominacionorigen')),
                ('tiposUva', models.ManyToManyField(related_name='TipoUva', to='main.tipouva')),
            ],
        ),
    ]
